### ISSUE TITLE
OpenNI dependency

### ISSUE THREAD

**Issue by ddiakopoulos** [leonidk/ps1080test#1]
Is it possible to refactor into multiple examples?
1) Consuming OpenNI camera
2) Taking arbitrary depth input (static image for example purposes)

**Comment by leonidk** [comment]
I think it's already done. 

This code has always had a generic Camera.h interface and a specific implementation ONICamera.h. For file reading/writing purposes, I might be interested in a FileCamera.h, but OpenNI provides it's own, fairly friendly, Recorder/Reader class so I'd likely build off that instead of rolling my own.
