### ISSUE TITLE
SDL / OSX

### ISSUE THREAD

**Issue by ddiakopoulos** [leonidk/ps1080test#2]
[SDL since Mavericks](http://joseph-long.com/writing/sdl-and-os-x/) has been annoying to consume. Possible to port the examples to GLFW?

**Comment by leonidk** [comment]
I've never developed on OSX, and since the conversion to Makefile+MSVC from CMake, it's not clear how well supported this code is on OSX. Since I don't have an Apple machine, I can't reliably test it. On Linux and Windows, I think SDL & GLFW are equally easy to consume. 

SDL2 seems fairly sensible to use according to that guide, and besides personal preference for SDL's API, currently GLFW lacks a simple 2D Render class (which is how I currently draw all my windows), and multi-touch. 

None of those are killers, but I don't foresee moving those code to GLFW yet. I'll be sure to link to that guide once I add a README.
